export const LOGIN_PATH = '/login'
export const REGISTRATION_PATH = '/registration'
export const POST_PATH = 'posts'
export const MY_POSTS_PATH = 'myPosts'
export const CREATE_UPDATE_POST_PATH = 'myPosts/:id'